### ISSUE TITLE
Style update issue when setting CSS variables using JS on the root element

### ISSUE THREAD

**Issue by bogdanbeniaminb** [nuxodin/ie11CustomProperties#33] opened 2020-01-26 17:57 UTC
When updating CSS variables on the root element, the CSS stylesheets don't get updated and the values on the child elements remain the same as on page load.

My workflow is as follows:
- I have some properties on some elements in the page. Some of these properties use values like `calc(var(--menu-space) + 10px)`, others use values like `var(--example, hidden)`;
- These CSS variables are set from JS (onScroll event listener) using style.setProperty on the *root* element, not on the child elements (e.g. `document.documentElement.style.setProperty('--menu-space', space + 'px');` );

Expected results:
The values of the properties on the elements should update when their values is changed on the root element (CSS inheritance).

Actual results:
The values remain the same as on page load. The rewritten styles aren't "redrawn" when the CSS variables are updated on the root element using JS.

P.S. Could you also perhaps expose the functions somehow (so that we could run stuff like `ie11CustomProperties.redrawStyleSheets()` when needed? I think it would also help with debugging).

Thank you!

**Comment by nuxodin** [comment] 2020-01-27 08:59
Hi, 

I made an update that should fix your problem.
Can you retest?

setProperty('--var','xy' ) will now trigger redrawStyleSheets to write root-properties

At the moment, i dont expose a api, because I don't want to drag these around in the future.

**Comment by bogdanbeniaminb** [comment] 2020-01-27 10:09
Thank you for the changes!

It's now working better, but there is still an issue (perhaps related to the changes in version 3). I have an element that has `top: calc(var(--menu-space, 0px)*-1);`. It seems the polyfill fails to process it (it seemed to work in 2.7.3) and it renders `top:0px)*-1` on page load. This also doesn't change when the CSS variable is changed on root using `setProperty('--menu-space', '100px')`, so I think it just silently fails to process it.

**Comment by nuxodin** [comment] 2020-01-27 14:19
Oh, yes, this was a bug with my new css-value-parser.
Now fixed with 3.0.2

**Comment by bogdanbeniaminb** [comment] 2020-01-28 07:27
Thank you! Could you push the new version to NPM? It still has the old version.

**Comment by nuxodin** [comment] 2020-01-28 14:44
oops... I forgot about that.
Done...

**Comment by bogdanbeniaminb** [comment] 2020-01-28 15:17
Thank you very much! It's closer to being perfect :)

There are still 2 issues now:

1. When I update the CSS variables on the root element using JS, the property on the child element remains one step backwards (it processes the value from before the change, not the new value).

2. Also, I noticed in the Inspector that there's an issue with multiple serial `calc` operations.
The original property is 
```
.gform-wrapper { 
  --space: calc(var(--full-menu-space, 0) + 10px); 
  top: calc(var(--space, 0px) * -1); 
  margin-bottom: calc(var(--space, 0px) * -1) !important;
}``` 
In the Inspector, I now have several
```
.gform-wrapper.iecp-u1 { 
  top: calc(calc(82px + 10px)*-1);
  margin-bottom: calc(calc(82px + 10px)*-1) !important;
}```
which is not valid (calc inside calc).

Thank you for your patience!

**Comment by nuxodin** [comment] 2020-01-28 18:16
Hi
I managed to fix the nested calc thing.

`calc(var(--space, 0px) * -1)`
now evaluates to 
`calc((82px + 10px)*-1)`

The algo is like that:
if var(--xyz) is inside calc(...) and the value of --xyz starts with 'calc(', 'calc' is stripped.

Bear in mind that IE has other issues with nested calc, mentoned on caniuse in "known issues":
https://caniuse.com/#search=calc
> IE11 is reported to have trouble with calc() with nested expressions, e.g. width: calc((100% - 10px) / 3); (i.e. it rounds differently)

**Comment by nuxodin** [comment] 2020-01-28 18:52
Now on npm :D

**Comment by bogdanbeniaminb** [comment] 2020-01-29 07:51
Hello, @nuxodin.

Thank you! This fixes the issue with nested calc. 

There is still the issue where properties with `calc(var(--space) + 10px)` are stuck one "step" backwards in history. I did some more testing and it doesn't happen when using simple `top: var(--space);`, but only when using `calc` (`top: calc(var(--space) + 10px);`). It seems like some kind of race condition? 

Thank you for your help!

**Comment by nuxodin** [comment] 2020-01-30 07:27
Hi Bogdanbeniaminb.

I need a reproducible example so i can look at the problem.
Maybe a PR to the tests? https://github.com/nuxodin/ie11CustomProperties/blob/master/tests.html

**Comment by bogdanbeniaminb** [comment] 2020-01-30 07:31
Hello, @nuxodin.

I'll try to make a test for this today.

Thank you!

**Comment by bogdanbeniaminb** [comment] 2020-01-30 13:14
Hello, @nuxodin .

I've just created a PR for a test to replicate the bug.

Thank you!

**Comment by nuxodin** [comment] 2020-01-30 20:10
Wow, great!
Thank you very mutch i accepted it.
As you wrote, the problem was the order of `redrawStyleSheets().` 
I saw that the problem appeared even without "calc" and changed your test case.

Thank you very much!

**Closed** 2020-01-30 20:11 UTC
